language: go
install:
  - grep 'import' -rl ./| xargs sed -i 's#"SlackTest/#"github.com/qingche123/SlackTest/#g'
  - more main.go
go:
  - 1.7.4
notifications:
  email:
    - guoxiaojie@onchain.com
    - zhouziyan@onchain.com
  on_success: always
  on_failure: always